name: Commitlint

on: [push, pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install required dependencies
        run: |
          sudo apt --only-upgrade install nodejs yarn
      - name: Print versions
        run: |
          node --version
          yarn --version
      - name: Install commitlint
        run: |
          yarn add conventional-changelog-conventionalcommits
          yarn add commitlint@latest

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: yarn commitlint --from HEAD~1 --to HEAD --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: yarn commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Run lint-staged
        run: npx lint-staged

      - name: Run lint
        run: yarn run lint

      - name: Run build
        run: yarn run build